name: Build and Test React App

on:
  workflow_dispatch:
  
  repository_dispatch:
    types: [trigger-event]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: "Get Current Date"
        id: today
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      - name: Use Date Output
        run: echo "The current date is ${{ steps.today.outputs.date }}"
      - name: Install NPM
        run: npm install
      - name: dispatch trigger
        run: |
          echo "repository_dispatch triggered"