name: Notify changes

# **What it does**: Triggers on changes to .github/workflows, sends email with commit details to admin

on:
  push:
    branches: ['main']
    paths:
      - '.github/workflows/**'

permissions:
  contents: read

jobs:
  Collect-commit:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Get Git SHA and changed path"
        id: GitSHAAndPath
        run: |
          echo "ShortID=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
          CHANGED_PATH=$(git log -1 --pretty=format:'%H - %p)

      - name: Print Last Commit Details
        run: |
          echo "Commit Hash: $GITHUB_SHA"
          echo "Branch Name: $GITHUB_REF"
          echo "Changed Path: ${{ steps.GitSHAAndPat.CHANGED_PATH }}"

      - uses: cinotify/github-action@main
        with:
          to: 'shatwarkn@gmail.com'
          subject: 'Building main'
          body: |
            This is a notification from GitHub actions.

            Commit Hash: ${{ steps.GitSHAAndPath.outputs.ShortID }}
            Branch Name: ${{ github.ref }}
            Changed Path: ${{ steps.GitSHAAndPath.CHANGED_PATH }}
