name: Notify changes

# **What it does**: Triggers on changes to .github/workflows, sends email with commit details to admin

on:
  push:
    branches: ['main']
    paths:
      - '.github/workflows/**'
  workflow_dispatch:
    inputs:
        paths : 
            type: choice
            required: true
            description: "Pipeline Run Path"
            options: 
                - '.github/workflows/**'

permissions:
  contents: read

jobs:
  Collect-commit:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Get Git SHA and changed path"
        id: GitSHAAndPath
        run: |
            echo "ShortID=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Print Last Commit Details
        run: |
          echo "Commit Hash: $GITHUB_SHA"
          echo "Branch Name: $GITHUB_REF"

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v42

  
      - name: List all changed files
        env:
            ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
            echo "${{env.ALL_CHANGED_FILES}}"

      - uses: cinotify/github-action@main
        env:
            ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        with:
          to: 'shatwarkn@gmail.com'
          subject: 'There is a new commit done to files in .github/workflows '
          body: |
            This is a notification from GitHub actions for the recent commit 

            Commit Hash: ${{ steps.GitSHAAndPath.outputs.ShortID }}
            Branch Name: ${{ github.ref }}
            changed file: ${{env.ALL_CHANGED_FILES}}
