name: Notify changes

# **What it does**: Triggers on changes to .github/workflows, sends email with commit details to admin. 

on:
  push:
    branches: ['main']
    paths:
      - '.github/workflows/**'
  workflow_dispatch:
    inputs:
        paths : 
            type: choice
            required: true
            description: "Pipeline Run Path"
            options: 
                - '.github/workflows/**'

permissions:
  contents: read

env:
    AUTHOR: ${{ github.event.pusher.name }}

jobs:
  Collect-commit-data:
    permissions:
      contents: read

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

# Get the Current Date and Time
      - name: Get current date time
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H:%M:%S')"

# Get the Git SHA
      - name: "Get Git SHA"
        id: GitSHAAndPath
        run: |
            echo "ShortID=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

# get the path where the change has occured.
      - name: Get changed files
        id: changed-files
        shell : pwsh
        run: |
            git config user.name "GitHubActions"
            git show --name-only ${{ steps.GitSHAAndPath.outputs.ShortID }} | Select-Object -Skip 6 
            $Changed_files = $(git show --name-only ${{ steps.GitSHAAndPath.outputs.ShortID }} | Select-Object -Skip 6)
            $path=@()
            $count=0
            foreach ($filepath in $Changed_files) {
                echo "Processing: $filepath"
                $count+=1
                $path+=("$count ",":- ", $filepath," ")
             } 
            echo "::set-output name=contentpath::$path"
            echo "::set-output name=pathchanged::$Changed_files"

# Print the Commit details 
      - name: Print Last Commit Details 
        run: |
            echo "Commit Hash: $GITHUB_SHA"
            echo "Branch Name: $GITHUB_REF" 
            echo "Changed File: '${{steps.changed-files.outputs.pathchanged}}'"      

# send a mail to admin regarding the change in the file in the folder .github/workflows
      - uses: cinotify/github-action@main
        with:
          to: 'shatwarkn@gmail.com'
          subject: 'There is a new commit done to files in .github/workflows '
          body: |
            This is a notification from GitHub actions for the recent commit done to the file in the .github/workflows folder.

            Commit done by: ${{env.AUTHOR}}
            Commit message : ${{ github.event.head_commit.message }}
            Date and Time : ${{ steps.date.outputs.date }}
            Commit Hash: ${{ steps.GitSHAAndPath.outputs.ShortID }}
            Branch Name: ${{ github.ref }}
            changed file: ${{steps.changed-files.outputs.contentpath}}

