name: Notify changes

# **What it does**: Triggers on changes to .github/workflows, sends email with commit details to admin

on:
  push:
    branches: ['main']
    paths:
      - '.github/workflows/**'
  workflow_dispatch:
    inputs:
        paths : 
            type: choice
            required: true
            description: "Pipeline Run Path"
            options: 
                - '.github/workflows/**'

permissions:
  contents: read

jobs:
  Collect-commit:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Get Git SHA and changed path"
        id: GitSHAAndPath
        run: |
            echo "ShortID=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Get changed files
        id: changed-files
        shell: pwsh
        run: |
            echo "CommitChangePath = git show --name-only ${{ steps.GitSHAAndPath.outputs.ShortID }} | Select-Object -Skip 6"

      - name: Print Last Commit Details 
        run: |
            echo "Commit Hash: $GITHUB_SHA"
            echo "Branch Name: $GITHUB_REF"   
            echo "Changed File:${{steps.changed-files.outputs.CommitChangePath}}"    

      - name: Fetch recent commits from thursday repo.
        id: fetch-commits-thursday 
        run: |
            folder_path=".github/workflows"  # Update this with the path to the folder in Repository A
            owner="shatwarkn29"
            repo="thursday"
            token="${{ secrets.TOKEN_THURSDAY }}"
            latest_commit=$(curl -s -H "Authorization: token $token" "https://api.github.com/repos/$owner/$repo/commits?path=$folder_path" | jq -r '.[0].sha')
            echo "COMMIT_A=$latest_commit"
            echo "$latest_commit"

      - uses: cinotify/github-action@main
        with:
          to: 'shatwarkn@gmail.com'
          subject: 'There is a new commit done to files in .github/workflows '
          body: |
            This is a notification from GitHub actions for the recent commit 

            Commit Hash: ${{ steps.GitSHAAndPath.outputs.ShortID }}
            Branch Name: ${{ github.ref }}
            changed file: ${{steps.changed-files.outputs.CommitChangePath}}
