name: Notify changes

# **What it does**: Triggers on changes to .github/workflows, sends email with commit details to admin

on:
  push:
    branches: ['main']
    paths:
      - '.github/workflows/**'

permissions:
  contents: read

jobs:
  Collect-commit:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Get Git SHA and changed path"
        id: GitSHAAndPath
        run: |
            echo "ShortID=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Print Last Commit Details
        run: |
          echo "Commit Hash: $GITHUB_SHA"
          echo "Branch Name: $GITHUB_REF"

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v42
        # NOTE: `since_last_remote_commit: true` is implied by default and falls back to the previous local commit.
  
      - name: List all changed files
        env:
            ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
            for file in ${ALL_CHANGED_FILES}; do
              echo "$file was changed"
            done

      - uses: cinotify/github-action@main
        env:
            ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        with:
          to: 'shatwarkn@gmail.com'
          subject: 'Building main'
          body: |
            This is a notification from GitHub actions.

            Commit Hash: ${{ steps.GitSHAAndPath.outputs.ShortID }}
            Branch Name: ${{ github.ref }}
            changed file: ${ALL_CHANGED_FILES}
